# Generated by Django 5.0.14 on 2025-05-12 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0003_alter_pago_dojo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='estado_pago',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=10),
        ),
    ]
