# Generated by Django 5.0.14 on 2025-05-13 14:35

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojos', '0003_alter_dojo_create_at_alter_dojo_update_at'),
        ('instructores', '0001_initial'),
        ('pagos', '0004_pago_estado_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='dojo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='dojos.dojo'),
        ),
        migrations.CreateModel(
            name='PagoInstructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('semana_inicio', models.DateField(help_text='Lunes de la semana trabajada')),
                ('semana_fin', models.DateField(help_text='Domingo de la semana trabajada')),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True)),
                ('estado_pago', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=10)),
                ('estado', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('dojo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_instructor', to='dojos.dojo')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='instructores.instructor')),
            ],
        ),
    ]
