# Generated by Django 5.0.1 on 2025-05-07 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='cinturon',
            field=models.CharField(choices=[('10.º kyū: Blanco', '10.º kyū: Blanco'), ('9.º kyū: Amarillo', '9.º kyū: Amarillo'), ('8.º kyū: Naranja', '8.º kyū: Naranja'), ('7.º kyū: Verde', '7.º kyū: Verde'), ('6.º kyū: Azul', '6.º kyū: Azul'), ('5.º kyū: Marrón', '5.º kyū: Marrón'), ('4.º kyū: Marrón', '4.º kyū: Marrón'), ('3.º kyū: Marrón', '3.º kyū: Marrón'), ('2.º kyū: Marrón', '2.º kyū: Marrón'), ('1.º kyū: Marrón', '1.º kyū: Marrón'), ('1.º dan: Cinturón negro', '1.º dan: Cinturón negro'), ('2.º dan: Cinturón negro', '2.º dan: Cinturón negro'), ('3.º dan: Cinturón negro', '3.º dan: Cinturón negro'), ('4.º dan: Cinturón negro', '4.º dan: Cinturón negro'), ('5.º dan: Cinturón negro', '5.º dan: Cinturón negro'), ('6.º dan: Cinturón negro', '6.º dan: Cinturón negro'), ('7.º dan: Cinturón negro', '7.º dan: Cinturón negro'), ('8.º dan: Cinturón negro', '8.º dan: Cinturón negro'), ('9.º dan: Cinturón negro', '9.º dan: Cinturón negro'), ('10.º dan: Cinturón negro', '10.º dan: Cinturón negro')], default='10.º kyū: Blanco', max_length=50),
        ),
        migrations.AddField(
            model_name='alumno',
            name='grupo',
            field=models.CharField(choices=[('Mañana', 'Mañana'), ('Tarde', 'Tarde'), ('Noche', 'Noche')], default='Mañana', max_length=20),
        ),
        migrations.AddField(
            model_name='alumno',
            name='matricula',
            field=models.CharField(choices=[('Matricula regular', 'Matrícula regular'), ('Matricula excepcional', 'Matrícula excepcional')], default='Matricula regular', max_length=30),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=10),
        ),
    ]
