# Generated by Django 5.0.14 on 2025-05-13 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0002_alumno_cinturon_alumno_grupo_alumno_matricula_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='cinturon',
        ),
    ]
