# Generated by Django 5.0.14 on 2025-05-13 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alumnos', '0003_remove_alumno_cinturon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=20)),
                ('nivel', models.PositiveIntegerField(help_text='Número del grado (ej: 10 para 10.º kyū, 1 para 1.º dan)')),
                ('color', models.CharField(max_length=30)),
                ('ambito', models.CharField(blank=True, choices=[('local', 'Local'), ('regional', 'Regional'), ('nacional', 'Nacional'), ('internacional', 'Internacional')], max_length=20, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['tipo', 'nivel'],
                'unique_together': {('tipo', 'nivel')},
            },
        ),
        migrations.CreateModel(
            name='HistorialGrado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_obtencion', models.DateField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.alumno')),
                ('grado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grados.grado')),
            ],
            options={
                'ordering': ['-fecha_obtencion'],
                'unique_together': {('alumno', 'grado')},
            },
        ),
    ]
