# Generated by Django 5.0.14 on 2025-05-16 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojos', '0003_alter_dojo_create_at_alter_dojo_update_at'),
        ('grados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grado',
            name='dojo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='grados', to='dojos.dojo'),
            preserve_default=False,
        ),
    ]
