# Generated by Django 5.0.14 on 2025-05-13 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examenes', '0003_rename_pago_examen_monto_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='examen',
            name='hora',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
