# Generated by Django 5.0.14 on 2025-05-13 14:35

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examenes', '0004_examen_hora'),
        ('instructores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examen',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='instructores.instructor'),
        ),
        migrations.AddField(
            model_name='examen',
            name='nota_aprobacion',
            field=models.DecimalField(decimal_places=2, default=Decimal('10'), max_digits=5),
        ),
    ]
