# Generated by Django 5.0.14 on 2025-05-17 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examenes', '0005_examen_instructor_examen_nota_aprobacion'),
        ('instructores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examen',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examenes', to='instructores.instructor'),
        ),
    ]
