# Generated by Django 5.0.14 on 2025-05-17 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examenes', '0007_evaluacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacion',
            name='nota',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
