# Generated by Django 5.0.14 on 2025-05-18 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examenes', '0008_alter_evaluacion_nota'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Evaluacion',
        ),
    ]
