# Generated by Django 5.0.14 on 2025-05-18 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examenes', '0009_delete_evaluacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnoexamen',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
