# Generated by Django 5.0.14 on 2025-05-13 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('horarios', '0001_initial'),
        ('instructores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='instructores.instructor'),
        ),
        migrations.AddField(
            model_name='alumnohorario',
            name='horario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumnos', to='horarios.horario'),
        ),
        migrations.AlterUniqueTogether(
            name='alumnohorario',
            unique_together={('alumno', 'horario')},
        ),
    ]
